---
title: "hw1"
author: "陳樞元"
date: "2019/7/11"
output: html_document
---
# Q:當地犯罪數是否與人口有關聯?
###### [桃園市刑事案件分類發生數、破獲數及嫌疑犯人數](https://data.gov.tw/dataset/25883)

###### [桃園市政府警察局轄區現住人口、性別比例及人口密度](https://data.gov.tw/dataset/26053)

# 載入套件
```{r}
library(readr)
library(dplyr)
library(reshape)
```
# 載入各區刑事案件數
```{r}
crime <- read_csv("桃園市刑事案件分類發生數、破獲數及嫌疑犯人數.csv")
```
# 整理資料(取平均、四捨五入)
```{r}
crime <- crime %>% 
group_by(breau) %>%
  summarise(avg_h_count = mean(h_count))

crime <- crime%>%
group_by(breau) %>%
  summarise(i = round(avg_h_count))
```
# 載入各區人口密度
```{r}
people <- read_csv("桃園市政府警察局轄區現住人口、性別比例及人口密度.csv")
```
# 整理資料(取平均、四捨五入、刪除欄目)
```{r}
people <- people %>%
group_by(breau) %>%
  summarise(avg_density = mean(density))

people <- people%>%
group_by(breau) %>%
  summarise(d = round(avg_density))

people <- people[-6,]
```
# 結合並選取欄目
```{r}
combine <- merge(crime, people, all = FALSE)

final <- select(combine, breau, d, i)
```
# 修改欄目名稱
```{r}
rename(final,c(breau = "轄區",d = "犯罪數",i = "人口密度(人口數/平方公里)"))
```